cc_test(
    name = "panda_test",
    srcs = [
        "table_test.cpp",
    ],
    deps = [
        "//src:panda_lib",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:private"],
) 
