cc_binary(
    name = "example1",
    srcs = [
        "example1.cpp",
        "utils.h",
    ],
    deps = [
        "//src:panda_lib",
        "@yaml-cpp",
    ],
    visibility = ["//visibility:public"],
)

