cc_library(
    name = "panda_lib",
    srcs = [
        "model/panda.h",
        "model/table.h",
        "model/row.h",
        "panda.h",
        "panda_cases.h",
        "panda_utils.h",
        "utils.h",
    ],
    deps = [
        "@fmt//:fmt",
    ],
    visibility = ["//visibility:public"],
)
