cc_binary(
    name = "panda",
    srcs = [
        "main.cpp",
        "model/table.cpp",
        "model/table.h",
        "model/attrs.h",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)
