cc_binary(
    name = "panda",
    srcs = [
        "main.cpp",
        "model/table.h",
        "model/row.h",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "panda_lib",
    srcs = [
        "model/table.h",
        "model/row.h",
    ],
    visibility = ["//visibility:public"],
)
